from setuptools import setup, find_packages

setup(
    name="agriboot",
    version="0.1.0",
    description="AI Farmer Advisory System",
    author="AgriBoot Team",
    packages=find_packages(),
    install_requires=[
        "pinecone",
        "sentence-transformers",
        "langchain",
        "langchain-community",
        "langchain-huggingface",
        "langchain-text-splitters",
        "pypdf",
        "pdfplumber",
        "spacy",
        "groq",
        "textblob",
        "fuzzywuzzy",
        "python-Levenshtein",
        "transformers",
        "torch",
        "streamlit",
        "fastapi",
        "uvicorn",
        "pydantic",
        "python-dotenv",
        "requests",
        "PyQt5",
    ],
    python_requires=">=3.11,<3.13",
)