KEYWORDS = {
    "CD": [
    "yellow leaves with spots",
    "leaf spots disease",
    "brown spots on leaves",
    "leaf blight",
    "wilt disease",
    "powdery mildew",
    "downy mildew",
    "fungal infection in crops",
    "bacterial infection in plants",
    "viral disease in crops",
    "leaf curl disease",
    "mosaic virus",
    "anthracnose disease",
    "rust disease",
    "root rot",
    "stem rot",
    "seedling blight",
    "damping off disease",
    "canker disease",
    "vascular wilt",
    "plant disease symptoms",
    "crop disease identification",
    "disease outbreak in crops",
    "plant pathogen infection",
    "fungicide for crop disease",
    "disease control in crops",
    "disease management in agriculture",
    "infected plant leaves",
    "plant disease diagnosis",
    "fungal growth on leaves",
    "disease spread in crops",
    "crop disease prevention"
],
    "FR": [
    "best fertilizer for crop growth",
    "fertilizer recommendation for crops",
    "urea or dap for crops",
    "npk fertilizer recommendation",
    "fertilizer dose per acre",
    "fertilizer schedule for crops",
    "fertilizer for flowering stage",
    "fertilizer for vegetative growth",
    "nitrogen deficiency solution",
    "phosphorus deficiency in plants",
    "potassium requirement for crops",
    "organic fertilizer recommendation",
    "micronutrient deficiency correction",
    "fertilizer for maize crop",
    "fertilizer for rice crop",
    "fertilizer for wheat crop",
    "balanced fertilizer for plants",
    "fertilizer application method",
    "fertilizer through drip irrigation",
    "fertigation schedule",
    "soil nutrient management",
    "fertilizer planning for farming"
]
,"HT": [
    "right time to harvest crops",
    "harvest maturity indicators",
    "crop harvesting stage",
    "optimal harvest time",
    "how to know crop is ready to harvest",
    "days to harvest crop",
    "harvest duration of crops",
    "signs of crop maturity",
    "harvesting season in india",
    "harvest timing for wheat",
    "harvest timing for rice",
    "harvest timing for maize",
    "harvest timing for vegetables",
    "best time to harvest fruits",
    "harvest readiness check",
    "crop maturity period",
    "harvest calendar for crops"
]
,"I": [
    "irrigation schedule for crops",
    "how often to water crops",
    "water requirement for crops",
    "drip irrigation system",
    "sprinkler irrigation",
    "irrigation methods in farming",
    "water saving techniques in agriculture",
    "irrigation frequency",
    "over irrigation symptoms",
    "under irrigation problem",
    "best irrigation method for crops",
    "irrigation during summer season",
    "soil moisture management",
    "smart irrigation system",
    "irrigation planning for farms",
    "water management in farming"
]
,"PC": [
    "pest control in crops",
    "how to control insects in plants",
    "aphids control",
    "bollworm control",
    "whitefly control",
    "stem borer control",
    "mites control",
    "termite control in farms",
    "best pesticide for crops",
    "organic pest control methods",
    "chemical pest control",
    "integrated pest management",
    "pest infestation solution",
    "crop protection from pests",
    "safe pesticide for vegetables",
    "insecticide recommendation",
    "pest management in agriculture"
]
,"SM": [
    "soil fertility improvement",
    "how to improve soil health",
    "soil testing for agriculture",
    "soil pH management",
    "organic matter in soil",
    "green manure benefits",
    "soil salinity management",
    "soil erosion control",
    "soil structure improvement",
    "best soil for crops",
    "soil preparation for farming",
    "soil conservation methods",
    "soil nutrient availability",
    "natural soil improvement techniques",
    "soil management practices"
]
,"M": [
    "tractor for farming",
    "farm machinery for sowing",
    "harvesting machines",
    "sprayer machine for agriculture",
    "rotavator vs cultivator",
    "paddy transplanting machine",
    "drone spraying in agriculture",
    "power tiller uses",
    "thresher machine",
    "low cost farm machinery",
    "agricultural equipment",
    "farm tools for farmers"
]

    ,
"MP": [
    "crop market price today",
    "commodity price in mandi",
    "price per quintal",
    "today vegetable price",
    "grain market rate",
    "crop selling price",
    "government crop price",
    "minimum support price",
    "price trend of crops",
    "local market price",
    "wholesale crop price",
    "agriculture market rate"
]


}
ZS_INTENTS = list(KEYWORDS.keys())